/**
 * ENGINE INVENTORY & ROLE MAP
 * ====================================================================
 * Every existing Precision Parity engine (and the meta/validation layers
 * around it) is classified here. Nothing is deleted; engines that are not
 * appropriate as a direct cell vote are classified, not discarded (§33).
 *
 * `correlationGroup` is what prevents 5 engines that all observe the same
 * underlying phenomenon from manufacturing 5 independent confirmations
 * (§10). Engines sharing a group are collapsed before weighting.
 */
import type { EngineRole } from "./types";

function role(r: EngineRole): EngineRole {
  return Object.freeze(r);
}

export const ENGINE_ROLES: Readonly<Record<string, EngineRole>> = Object.freeze({
  // ── Layer 1 — pure feature engines (direct evidence) ────────────────────
  stats: role({
    engine: "stats",
    family: "STATISTICAL",
    authority: "DIRECT",
    canHardVeto: false,
    canSoftEvidence: true,
    correlationGroup: "DISTRIBUTION",
    stage: "EVIDENCE",
    description: "Windowed even/odd rates with Wilson bounds (stats-engine.ts).",
  }),
  multiHorizon: role({
    engine: "multiHorizon",
    family: "STATISTICAL",
    authority: "META",
    canHardVeto: false,
    canSoftEvidence: true,
    correlationGroup: "DISTRIBUTION",
    stage: "META",
    description: "Short/medium/long horizon agreement derived from stats (multi-horizon-engine.ts).",
  }),
  markov: role({
    engine: "markov",
    family: "SEQUENCE",
    authority: "DIRECT",
    canHardVeto: false,
    canSoftEvidence: true,
    correlationGroup: "TRANSITION",
    stage: "EVIDENCE",
    description: "Variable-order parity transition model (markov-engine.ts).",
  }),
  pattern: role({
    engine: "pattern",
    family: "PATTERN",
    authority: "DIRECT",
    canHardVeto: false,
    canSoftEvidence: true,
    correlationGroup: "TRANSITION",
    stage: "EVIDENCE",
    description: "N-gram motif mining over the parity string (pattern-engine.ts).",
  }),
  runs: role({
    engine: "runs",
    family: "SEQUENCE",
    authority: "DIRECT",
    canHardVeto: false,
    canSoftEvidence: true,
    correlationGroup: "RUN_HAZARD",
    stage: "EVIDENCE",
    description: "Run-length hazard / exhaustion analysis (run-hazard-engine.ts).",
  }),
  pressure: role({
    engine: "pressure",
    family: "PRESSURE",
    authority: "DIRECT",
    canHardVeto: false,
    canSoftEvidence: true,
    correlationGroup: "IMBALANCE",
    stage: "EVIDENCE",
    description: "Cumulative imbalance z-score, momentum vs mean-reversion (pressure-engine.ts).",
  }),
  anomaly: role({
    engine: "anomaly",
    family: "ANOMALY",
    authority: "DIRECT",
    canHardVeto: false,
    canSoftEvidence: true,
    correlationGroup: "IMBALANCE",
    stage: "EVIDENCE",
    description: "Recent-vs-baseline surge detection (anomaly-engine.ts).",
  }),
  structural: role({
    engine: "structural",
    family: "STRUCTURAL",
    authority: "DIRECT",
    canHardVeto: false,
    canSoftEvidence: true,
    correlationGroup: "STRUCTURE",
    stage: "EVIDENCE",
    description: "Green/red bar structure, crowding, reversal probability (structural.ts).",
  }),
  hmm: role({
    engine: "hmm",
    family: "REGIME",
    authority: "DIRECT",
    canHardVeto: false,
    canSoftEvidence: true,
    correlationGroup: "REGIME",
    stage: "EVIDENCE",
    description: "Hidden-regime filter over the parity stream (hmm.ts).",
  }),
  regime: role({
    engine: "regime",
    family: "REGIME",
    authority: "CONTEXT",
    canHardVeto: false,
    canSoftEvidence: true,
    correlationGroup: "REGIME",
    stage: "EVIDENCE",
    description: "Stream regime classification + adaptive engine weights (regime-engine.ts).",
  }),
  particles: role({
    engine: "particles",
    family: "STATISTICAL",
    authority: "META",
    canHardVeto: true,
    canSoftEvidence: true,
    correlationGroup: "POSTERIOR",
    stage: "META",
    description: "Sequential particle filter posterior + weight-collapse detection (particle-filter.ts).",
  }),
  entropy: role({
    engine: "entropy",
    family: "ANOMALY",
    authority: "GATE",
    canHardVeto: true,
    canSoftEvidence: false,
    correlationGroup: "ENTROPY",
    stage: "GOVERNANCE",
    description: "Multi-window binary entropy; near-uniform noise veto (entropy-engine.ts).",
  }),
  changepoint: role({
    engine: "changepoint",
    family: "REGIME",
    authority: "META",
    canHardVeto: false,
    canSoftEvidence: false,
    correlationGroup: "REGIME_BREAK",
    stage: "META",
    description: "CUSUM changepoint detection and history discount factor (changepoint-engine.ts).",
  }),
  personality: role({
    engine: "personality",
    family: "REGIME",
    authority: "CONTEXT",
    canHardVeto: false,
    canSoftEvidence: false,
    correlationGroup: "SYMBOL_PRIOR",
    stage: "META",
    description: "Per-symbol behavioural prior (personality-engine.ts).",
  }),

  // ── Layer 2 — meta / validation ─────────────────────────────────────────
  decorrelation: role({
    engine: "decorrelation",
    family: "META",
    authority: "META",
    canHardVeto: false,
    canSoftEvidence: false,
    correlationGroup: "DECORRELATION",
    stage: "META",
    description: "Clusters correlated engines, reports effective vote count (decorrelation.ts).",
  }),
  significance: role({
    engine: "significance",
    family: "VALIDATION",
    authority: "META",
    canHardVeto: false,
    canSoftEvidence: true,
    correlationGroup: "SIGNIFICANCE",
    stage: "VALIDATION",
    description: "Bootstrap statistic, p/q values, Benjamini-Hochberg (significance.ts).",
  }),
  drift: role({
    engine: "drift",
    family: "REGIME",
    authority: "GATE",
    canHardVeto: true,
    canSoftEvidence: false,
    correlationGroup: "REGIME_BREAK",
    stage: "GOVERNANCE",
    description: "CUSUM + Page-Hinkley concept-drift detection (drift.ts).",
  }),
  conformal: role({
    engine: "conformal",
    family: "CALIBRATION",
    authority: "META",
    canHardVeto: false,
    canSoftEvidence: false,
    correlationGroup: "CALIBRATION",
    stage: "VALIDATION",
    description: "Conformal prediction interval over journal outcomes (conformal.ts).",
  }),
  calibration: role({
    engine: "calibration",
    family: "CALIBRATION",
    authority: "META",
    canHardVeto: false,
    canSoftEvidence: false,
    correlationGroup: "CALIBRATION",
    stage: "VALIDATION",
    description: "Reliability bins / confidence recalibration (calibration.ts, calibration-engine.ts).",
  }),
  evGate: role({
    engine: "evGate",
    family: "RISK",
    authority: "GATE",
    canHardVeto: true,
    canSoftEvidence: false,
    correlationGroup: "EV",
    stage: "GOVERNANCE",
    description: "Expected value / Kelly admission gate (ev-gate.ts, ev-gate-engine.ts).",
  }),
  danger: role({
    engine: "danger",
    family: "RISK",
    authority: "GATE",
    canHardVeto: true,
    canSoftEvidence: false,
    correlationGroup: "DANGER",
    stage: "GOVERNANCE",
    description: "Threat composition and critical veto (danger-engine.ts).",
  }),
  quality: role({
    engine: "quality",
    family: "INFRASTRUCTURE",
    authority: "GATE",
    canHardVeto: true,
    canSoftEvidence: false,
    correlationGroup: "FEED",
    stage: "GOVERNANCE",
    description: "Tick feed integrity / staleness veto (market-quality-engine.ts).",
  }),
  confluence: role({
    engine: "confluence",
    family: "META",
    authority: "META",
    canHardVeto: false,
    canSoftEvidence: true,
    correlationGroup: "CONFLUENCE",
    stage: "META",
    description: "Weighted composite of the direct engines (confluence-engine.ts).",
  }),
  ensemble: role({
    engine: "ensemble",
    family: "CALIBRATION",
    authority: "META",
    canHardVeto: false,
    canSoftEvidence: false,
    correlationGroup: "ADAPTIVE_WEIGHTS",
    stage: "META",
    description: "Outcome-weighted adaptive engine accuracy learner (ensemble-engine.ts).",
  }),
  walkForward: role({
    engine: "walkForward",
    family: "VALIDATION",
    authority: "META",
    canHardVeto: false,
    canSoftEvidence: false,
    correlationGroup: "VALIDATION",
    stage: "VALIDATION",
    description: "Walk-forward out-of-sample validation dashboard (walk-forward.ts).",
  }),
  shadow: role({
    engine: "shadow",
    family: "VALIDATION",
    authority: "META",
    canHardVeto: false,
    canSoftEvidence: false,
    correlationGroup: "VALIDATION",
    stage: "VALIDATION",
    description: "Paper-trade / backtest recorder (shadow-engine.ts).",
  }),

  // ── Timing, risk, entry, orchestration ──────────────────────────────────
  timing: role({
    engine: "timing",
    family: "TIMING",
    authority: "CONTEXT",
    canHardVeto: false,
    canSoftEvidence: false,
    correlationGroup: "TIMING",
    stage: "META",
    description: "Entry timing / urgency instruction (timing-engine.ts).",
  }),
  decay: role({
    engine: "decay",
    family: "TIMING",
    authority: "CONTEXT",
    canHardVeto: false,
    canSoftEvidence: false,
    correlationGroup: "TIMING",
    stage: "META",
    description: "Signal freshness decay (decay-engine.ts).",
  }),
  riskStake: role({
    engine: "riskStake",
    family: "RISK",
    authority: "CONTEXT",
    canHardVeto: false,
    canSoftEvidence: false,
    correlationGroup: "SIZING",
    stage: "GOVERNANCE",
    description: "Fractional Kelly stake sizing (risk-stake-engine.ts).",
  }),
  entryCriteria: role({
    engine: "entryCriteria",
    family: "ENTRY_DIGIT",
    authority: "CONTEXT",
    canHardVeto: false,
    canSoftEvidence: false,
    correlationGroup: "ENTRY",
    stage: "ENTRY",
    description: "Entry-condition construction (entry-criteria-engine.ts).",
  }),
  specificEntryDigit: role({
    engine: "specificEntryDigit",
    family: "ENTRY_DIGIT",
    authority: "CONTEXT",
    canHardVeto: false,
    canSoftEvidence: false,
    correlationGroup: "ENTRY",
    stage: "ENTRY",
    description:
      "Downstream trigger-digit selection: transition occurrences, Laplace smoothing, Wilson lower bound, edge, stability, expected wait, momentum, sample authority, composite score (specific-entry-digit.ts). Runs only after a cell establishes a legitimate direction.",
  }),
  contractSelector: role({
    engine: "contractSelector",
    family: "ORCHESTRATION",
    authority: "CONTEXT",
    canHardVeto: false,
    canSoftEvidence: false,
    correlationGroup: "FORMATTING",
    stage: "FORMATTING",
    description: "Maps a parity decision to a Deriv contract (contract-selector-engine.ts).",
  }),
  signalBuilder: role({
    engine: "signalBuilder",
    family: "ORCHESTRATION",
    authority: "CONTEXT",
    canHardVeto: false,
    canSoftEvidence: false,
    correlationGroup: "FORMATTING",
    stage: "FORMATTING",
    description: "Canonical FinalSignal formatter (signal-builder.ts, final-signal.ts).",
  }),
  forecast: role({
    engine: "forecast",
    family: "META",
    authority: "META",
    canHardVeto: false,
    canSoftEvidence: false,
    correlationGroup: "NARRATIVE",
    stage: "META",
    description: "Multi-model forward projection consumed by the existing pipeline (forecast.ts).",
  }),
  analysts: role({
    engine: "analysts",
    family: "META",
    authority: "META",
    canHardVeto: false,
    canSoftEvidence: false,
    correlationGroup: "NARRATIVE",
    stage: "META",
    description: "Bull/Bear/Chief/Contrarian dialectic panel (analysts.ts).",
  }),
  deepReasoning: role({
    engine: "deepReasoning",
    family: "META",
    authority: "META",
    canHardVeto: false,
    canSoftEvidence: false,
    correlationGroup: "NARRATIVE",
    stage: "META",
    description: "Long-form reasoning narrative (deep-reasoning.ts).",
  }),
  journal: role({
    engine: "journal",
    family: "INFRASTRUCTURE",
    authority: "CONTEXT",
    canHardVeto: false,
    canSoftEvidence: false,
    correlationGroup: "INFRA",
    stage: "VALIDATION",
    description: "Outcome journal feeding calibration/conformal (journal.ts).",
  }),
  sentinel: role({
    engine: "sentinel",
    family: "STRUCTURAL",
    authority: "GATE",
    canHardVeto: true,
    canSoftEvidence: true,
    correlationGroup: "SENTINEL",
    stage: "GOVERNANCE",
    description:
      "External structural authority. Consumed read-only through the cross-confirmation bridge; never re-implemented here (§16).",
  }),
  dbotReplay: role({
    engine: "dbotReplay",
    family: "VALIDATION",
    authority: "META",
    canHardVeto: false,
    canSoftEvidence: false,
    correlationGroup: "REPLAY",
    stage: "VALIDATION",
    description: "Exact OPEN/SETTLE replay of a candidate entry digit (dbot/replay-validator.ts).",
  }),
});

export function getEngineRole(engine: string): EngineRole {
  const found = ENGINE_ROLES[engine];
  if (found) return found;
  return Object.freeze({
    engine,
    family: "META",
    authority: "META",
    canHardVeto: false,
    canSoftEvidence: true,
    correlationGroup: `UNCLASSIFIED:${engine}`,
    stage: "META",
    description: "Unclassified engine — treated as low-authority soft evidence.",
  });
}

export const ENGINE_INVENTORY: readonly EngineRole[] = Object.freeze(Object.values(ENGINE_ROLES));
